{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra-demo.fullname" . }}
  labels:
    {{- include "infra-demo.labels" . | nindent 4 }}
data:
  {{- range $name, $config := .Values.configmap.values }}
  {{ $name }}: {{ $config | quote }}
  {{- end }}
{{- end }}