apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra-demo.fullname" . }}
  labels:
    {{- include "infra-demo.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "infra-demo.selectorLabels" . | nindent 4 }}
